/**
 * LLM Client for generating AI-powered health advice
 * Uses Google Gemini API
 */

/**
 * Generate personalized health advice based on risk prediction
 * @param {Object} params - { features, prediction, previousRecord }
 * @returns {Promise<string>} - AI-generated advice text
 */
async function generateAdvice({ features, prediction, previousRecord = null }) {
  // 1. Clean the key (trim whitespace)
  const apiKey = process.env.GEMINI_API_KEY ? process.env.GEMINI_API_KEY.trim() : '';
  
  if (!apiKey || apiKey === 'your_gemini_api_key_here') {
    console.warn('⚠️  GEMINI_API_KEY not configured, using placeholder advice');
    return generatePlaceholderAdvice({ features, prediction, previousRecord });
  }

  const prompt = buildPrompt({ features, prediction, previousRecord });
  
  console.log('🤖 Calling Gemini API for health advice...');

  try {
    // Use the correct model name: gemini-1.5-flash-latest
    const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=${apiKey}`;
    
    const response = await fetch(apiUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: prompt
          }]
        }],
        generationConfig: {
          temperature: 0.7,
          maxOutputTokens: 10000000,
          topP: 0.95,
          topK: 40
        }
      })
    });

    if (!response.ok) {
      const errorText = await response.text();
      // Log the full error text to help debugging
      console.error('Gemini API Response:', errorText);
      throw new Error(`Gemini API error: ${response.status} - ${errorText}`);
    }

    const data = await response.json();
    
    // Debug: Log the full response structure
    console.log('Gemini API Response:', JSON.stringify(data, null, 2));
    
    // Try to extract text from different possible response formats
    let adviceText = null;
    
    if (data.candidates?.[0]?.content?.parts?.[0]?.text) {
      adviceText = data.candidates[0].content.parts[0].text;
    } else if (data.candidates?.[0]?.text) {
      adviceText = data.candidates[0].text;
    } else if (data.text) {
      adviceText = data.text;
    }
    
    if (!adviceText) {
      const finishReason = data.candidates?.[0]?.finishReason;
      console.error('Finish Reason:', finishReason);
      console.error('Response structure:', JSON.stringify(data, null, 2));
      
      if (finishReason === 'MAX_TOKENS') {
        throw new Error('Response truncated: MAX_TOKENS reached. Increase maxOutputTokens.');
      }
      
      throw new Error('Invalid response format from Gemini API');
    }
    
    console.log('✅ Gemini advice generated successfully');

    const disclaimer = '\n\n⚠️ This advice is generated by an AI system and is for information and education only. It is NOT a medical diagnosis or a substitute for professional medical advice, diagnosis, or treatment. Always talk to a qualified healthcare professional before making decisions about your health.';

    return `${adviceText}${disclaimer}`;
    
  } catch (error) {
    console.error('❌ Gemini API error:', error.message);
    console.warn('⚠️  Falling back to placeholder advice');
    return generatePlaceholderAdvice({ features, prediction, previousRecord });
  }
}

/**
 * Build prompt for LLM based on user features and prediction
 * @param {Object} params - { features, prediction, previousRecord }
 * @returns {string} - Formatted prompt
 */
function buildPrompt({ features, prediction, previousRecord = null }) {
  const { age_years, bmi, ap_hi, ap_lo, cholesterol, gluc, smoke, alco, ACTIVE } = features;
  const { probability, label } = prediction.stacked;

  let prompt = `You are a health advisor. Patient: ${age_years}yo, BMI ${bmi.toFixed(1)}, BP ${ap_hi}/${ap_lo}, Chol=${cholesterol}, Gluc=${gluc}, Smoke=${smoke ? 'Yes' : 'No'}, Alcohol=${alco ? 'Yes' : 'No'}, Active=${ACTIVE ? 'Yes' : 'No'}.

CVD Risk: ${label} (${(probability * 100).toFixed(1)}%).`;

  // Add historical context if available
  if (previousRecord) {
    const prevDate = new Date(previousRecord.recorded_at).toLocaleDateString();
    const prevBmi = parseFloat(previousRecord.bmi) || 0;
    const bmiChange = (bmi - prevBmi).toFixed(1);
    const bpChange = (ap_hi - previousRecord.ap_hi);
    const riskChange = label !== previousRecord.risk_label;
    
    prompt += `\n\nPrevious Record (${prevDate}): BMI ${prevBmi.toFixed(1)}, BP ${previousRecord.ap_hi}/${previousRecord.ap_lo}, Risk: ${previousRecord.risk_label} (${(previousRecord.stacked_probability * 100).toFixed(1)}%).

Changes: BMI ${bmiChange > 0 ? '+' : ''}${bmiChange}, BP ${bpChange > 0 ? '+' : ''}${bpChange}/${(ap_lo - previousRecord.ap_lo)}${riskChange ? `, Risk changed from ${previousRecord.risk_label} to ${label}` : ''}.`;
  }

  prompt += `\n\nProvide in 200 words:
1. ${previousRecord ? 'Progress assessment and current status' : 'Brief risk assessment'} (2 sentences)
2. Top 3 specific ${previousRecord ? 'next steps based on progress' : 'lifestyle changes'}
3. When to see a doctor

Be supportive and actionable.`;

  return prompt;
}

/**
 * Generate placeholder advice when Gemini API is not configured
 * @param {Object} params - { features, prediction, previousRecord }
 * @returns {string} - Placeholder advice text
 */
function generatePlaceholderAdvice({ features, prediction, previousRecord = null }) {
  const { age_years, bmi, ap_hi, smoke, ACTIVE } = features;
  const { probability, label } = prediction.stacked;

  let advice = `At ${age_years} years old, your cardiovascular disease risk is assessed as ${label} (${(probability * 100).toFixed(1)}% probability).\n\n`;

  // Add progress comparison if previous record exists
  if (previousRecord) {
    const prevDate = new Date(previousRecord.recorded_at).toLocaleDateString();
    const daysSince = Math.floor((new Date() - new Date(previousRecord.recorded_at)) / (1000 * 60 * 60 * 24));
    
    advice += `📊 Progress Since ${prevDate} (${daysSince} days ago):\n`;
    
    // BMI comparison
    const prevBmi = parseFloat(previousRecord.bmi) || 0;
    const bmiChange = bmi - prevBmi;
    if (Math.abs(bmiChange) > 0.5) {
      advice += `• BMI: ${prevBmi.toFixed(1)} → ${bmi.toFixed(1)} (${bmiChange > 0 ? '+' : ''}${bmiChange.toFixed(1)}) ${bmiChange < 0 ? '✅' : '⚠️'}\n`;
    }
    
    // Blood pressure comparison
    const bpChange = ap_hi - previousRecord.ap_hi;
    if (Math.abs(bpChange) > 5) {
      advice += `• Blood Pressure: ${previousRecord.ap_hi}/${previousRecord.ap_lo} → ${ap_hi}/${features.ap_lo} (${bpChange > 0 ? '+' : ''}${bpChange}) ${bpChange < 0 ? '✅' : '⚠️'}\n`;
    }
    
    // Risk level comparison
    if (label !== previousRecord.risk_label) {
      const riskImproved = (label === 'Low' && previousRecord.risk_label !== 'Low') || 
                          (label === 'Moderate' && previousRecord.risk_label === 'High');
      advice += `• Risk Level: ${previousRecord.risk_label} → ${label} ${riskImproved ? '✅' : '⚠️'}\n`;
    }
    
    advice += '\n';
  }

  // Risk factors
  const riskFactors = [];
  if (ap_hi > 140) riskFactors.push('elevated blood pressure');
  if (bmi > 30) riskFactors.push('high BMI');
  if (smoke === 1) riskFactors.push('smoking');
  if (ACTIVE === 0) riskFactors.push('low physical activity');

  if (riskFactors.length > 0) {
    advice += `Key risk factors identified: ${riskFactors.join(', ')}.\n\n`;
  }

  // Recommendations
  advice += 'Recommendations:\n';
  if (ap_hi > 140) advice += '• Monitor and manage your blood pressure through diet and medication if prescribed\n';
  if (bmi > 30) advice += '• Consider a balanced diet and gradual weight management program\n';
  if (smoke === 1) advice += '• Seek support to quit smoking - this is the single most impactful change\n';
  if (ACTIVE === 0) advice += '• Aim for 150 minutes of moderate exercise per week\n';
  
  advice += '\n⚠️ This is an AI-generated assessment. Please consult with a healthcare provider for personalized medical advice.';

  return advice;
}

export { generateAdvice };
